update daemon script

diff --git a/start-judge-daemon b/start-judge-daemon
--- a/start-judge-daemon
+++ b/start-judge-daemon
@@ -9,18 +9,22 @@ fi
 mkdir -p logs
 
 function test-start {
-	if [[ "$1" == "$2" || "$1" == "all" ]]; then
-		ID=`pgrep -f "judgedaemon $2"`
-		if [[ $? == 1 ]]; then
-			echo "starting $2 daemon."
-			cp "judgehost/etc/restapi.secret.$2" judgehost/etc/restapi.secret
-			php ./judgehost/bin/judgedaemon $2 &> "logs/daemon-$2.log" &
-		else
-			echo "$2 daemon already running as $ID"
-		fi
-	fi
+        if [[ "$1" == "$2" || "$1" == "all" || "$1" == "" ]]; then
+                GOT=1
+                ID=`pgrep -f "judgedaemon $2"`
+                if [[ $? == 1 ]]; then
+                        echo "starting $2 daemon."
+                        cp "judgehost/etc/restapi.secret.$2" judgehost/etc/restapi.secret
+                        php ./judgehost/bin/judgedaemon $2 &> "logs/daemon-$2.log" &
+                else
+                        echo "$2 daemon already running as $ID"
+                fi
+        fi
 }
 
+GOT=0
 test-start "$1" "local"
 test-start "$1" "test"
 test-start "$1" "main"
+
+[[ $GOT == 0 ]] && echo "Invalid daemon $1. No daemons started."
